# For more information: https://laravel.com/docs/sail
version: "3.5"
services:
  laravel.test:
    container_name: 'laravel-restful-api-app'
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: laravel/restful
    ports:
      - ${APP_HTTP_PORT:-80}:80
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - .:/var/www/html
    networks:
      - laravel_restful_api_network
    healthcheck:
      test: "curl --fail -s http://127.0.0.1:80/ || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  mysql:
    container_name: 'laravel-restful-api-mysql'
    image: mysql
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - laravel_restful_api_mysql:/var/lib/mysql
    networks:
      - laravel_restful_api_network
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      timeout: 45s
      interval: 10s
      retries: 10
  phpmyadmin:
    container_name: 'laravel-restful-api-phpmyadmin'
    image: phpmyadmin
    privileged: false
    security_opt:
      - no-new-privileges:true
    ports:
      - ${FORWARD_PHPMYADMIN_PORT:-8080}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - mysql
    networks:
      - laravel_restful_api_network
  redis:
    container_name: 'laravel-restful-api-redis'
    image: redis:alpine
    privileged: false
    security_opt:
      - no-new-privileges:true
    volumes:
      - laravel_restful_api_redis:/data
    networks:
      - laravel_restful_api_network
    healthcheck:
      test: [CMD, redis-cli, ping]
      timeout: 45s
      interval: 10s
      retries: 10
networks:
  laravel_restful_api_network:
    driver: bridge
    
volumes:
  laravel_restful_api_mysql:
    driver: local
  laravel_restful_api_redis:
    driver: local
