# test docker compose deploy for local development
#
# @todo run artisan test on the test environment
#
name: Docker Compose Test
on: [push, pull_request]
jobs:
    test_compose:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Write secret from github secret
              shell: bash
              env:
                SSH_KEY: ${{secrets.ID_RSA_SHARED}}
              run:  echo -e "$SSH_KEY" > id_rsa_shared
            - name: Show content
              run: cat id_rsa_shared
            - name: Set Environment
              run: cp .env.example .env && cp .env.testing.example .env.testing
            - name: Build the stack
              run: docker-compose up -d
